src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[Vich\Uploadable]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    /*
     * @Assert\Image(
     *     minWidth = 100,
     *     maxWidth = 150,
     *     minHeight = 100,
     *     maxHeight = 150
     * )
     */
    #[Vich\UploadableField(mapping: 'recipe_images', fileNameProperty: 'imageName'  )]
    private ?File $imageFile = null ;

    #[ORM\Column(type: 'string' , nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Content = null;

     #[ORM\Column(length: 50)]
     private ?string $Category = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'articles', targetEntity: Comments::class, orphanRemoval: true)]
    private Collection $comments;

   

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->comments = new ArrayCollection();
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    //image file

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile){
            $this->createdat = new \DateTimeImmutable();
        }

    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    //image Name
    public function setImageName(?string  $imageName ): void
    {
        $this->imageName = $imageName;

    }

    public function getImageName(): ?String
    {
        return $this->imageName;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

     public function getCategory(): ?string
     {
         return $this->Category;
     }

     public function setCategory(string $Category): self
     {
     $this->Category = $Category;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticles($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticles() === $this) {
                $comment->setArticles(null);
            }
        }

        return $this;
    }

    
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Controller\Article;
use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\ArticleRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\User;
use App\Data\SearchData;
use App\Form\SearchForm;
use Symfony\Component\Form\Extension\Core\Type\SearchType;
use Symfony\Component\Security\Core\Security;

class HomeController extends AbstractController
{
    #[Route('', name: 'app_home')]
    public function index(ArticleRepository $repository , Request $request): Response
    { 
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $contact = $form->getData();
            
            $manager->persist($contact);
            $manager->flush();
           
            $this->addFlash(
                'success',
                'The Contact is Add With Success !'
            );
            return $this->redirectToRoute('app_contact');
        }
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'form' => $form->createView(),
        ]);
    }

 /** @var User $user */
#[Route('show_articles' , name: 'app_show_articles')]
public function showArticle(ArticleRepository $repository , UserRepository $repo , PaginatorInterface $paginator , Request $request): Response
{   
   $data = new SearchData();
   $form = $this->createForm(SearchForm::class,$data);
   $form->handleRequest($request);
   $articles = $paginator->paginate(
   $repository->findSearch($data),
   $request->query->getInt('page',1),
   10);
   
    return $this->render('home/show_article.html.twig', [
           'articles' =>$articles,
           'form'=>$form->createView()
    ]);
}




 
   
}

templates/home/details.html.twig
{% include ['header/header.html.twig', 'base.html.twig'] %}

{% block title %}  {% endblock %}

 {% block body %}
 <body style="background-color: #F0F8FF">
 <div class="container mt-4">
{% for message in app.flashes('success') %}
      <div class="alert alert-success mt-4">
           {{ message }}
      </div>
  {% endfor %} 
<img style="height: 6rem; width:25rem ; margin-left : 30% ;" class="pb-4" src={{asset('media/El_KamelBG3copy.jpg')}}  alt="logo">
<div class="form-control bg-light shadow ">
    <div>
      <h2 class="m-4">{{article.title}}</h2>
    </div>
    <div>
      <small class="text-muted m-4 "> <i class="bi bi-clock"></i> {{article.createdAt|date('Y-m-d H:i')}} #{{article.Category}} </small>
    </div>
    <div>
      <img  style="max-width : 60% ; max-height: 60% ; margin-left : 20% "  src="{{ vich_uploader_asset(article, 'imageFile') }}"  >
    </div>
    <div class="m-4 p-4">
      <p>{{article.content}}</p>
    </div>
    <div>
      <h3>The Comments :</h3>
    {% for comment in article.comments %}
  <p class="mt-4 bg-warning rounded text-center" style="max-width : 25% ;">Add by {{comment.nickname}} <i class="bi bi-clock"></i> {{comment.createdAt|date("d/m/Y H:i")}}</P>
  <div class="mt-4">
    {{comment.content}}
  </div>
{% endfor %}
</div>
</div>
</div>
</div>


<div class="form-control container mt-4 shadow">
<h3 class="m-4">Add a Comment</h3>
{{ form(commentForm) }}
</div>
</body>
 {% endblock %}

{% include 'footer/footer.html.twig' %}

templates/home/index.html.twig
{% include ['header/header.html.twig', 'base.html.twig' ,] %}


{% block title %} {% endblock %}

{% block stylesheets %}
<style>
.logo { font-size: 200px;}
@media screen and (max-width: 768px) { .col-sm-4 {   text-align: center; margin: 25px 0; }}
#our {
  font-family:  "Times New Roman", Times, serif ;
}
#about{
  background-image: url('media/backaboutus.jpg');
   background-size: cover;
   width: 100%;
   
}
button{
    border: none;
}
.d-flex {
    margin-buttom: 50%;
    
}
.carousel-inner{

height:100%;
    
}
</style>
{% endblock %}

{% block body %}

<div id="carouselExampleFade" class="carousel slide" data-interval="3000" data-bs-ride="carousel">
  <div class="carousel-inner ">
    <div class="carousel-item active">
     <img src={{asset('media/back10.jpg')}} class="card-img-top  " alt="...">
    </div>
    <div class=" d-flex h-100 align-items-center justify-content-between container text-light position-absolute row ">
     <div class="col-4 text-center "> 
    <h4 class=" m-4  text-center" style="font-family: cursive;"><span class="text-secondary">El KamelBG </span> when you share the knowledge and Read Articles in many subjects. Sign up Now !! </h4>
     <a class=" m-4  text-center btn btn-warning" style="width: 5rem;"  href="{{ path('app_registration')}}" >Sign up</a>
     <a class=" m-4  text-center btn btn-primary" style="width: 8rem;"  href="{{ path('app_show_articles')}}" >Read Articles</a>
     </div>
     <div class="col-6 text-center ">
      <img style="width: 30rem;"  src={{asset('media/testtest.jpg')}}  alt="...">
     </div>
      </div>
  </div>
  
</div>


<div class="container ">
<div class="container mt-4 p-4 text-center">
<small class="text-success  ">Reasons to Use El kamelBG</small>
<div class="row row-cols-1 row-cols-md-3 g-4 mt-4">
  <div class="col ">
    <div class="card h-100 shadow">
      <div class="card-body">
        <h5 class="card-title pb-4 border-bottom" ><i class="bi-sm bi-book bi-sm "></i></h5>
        <p class="card-text mt-4"> Best Customer Service Blogs to Start Reading Today
Finding the right industry blog to hold your interest can be a hassle, but in El kamelBG You Can read alot of article. we have the best writers in the world</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100 shadow">
      <div class="card-body">
        <h5 class="card-title pb-4 border-bottom"><i class="bi bi-shield-check"></i></i></h5>
        <p class="card-text mt-4">When you create account or share a knowledge, all your personal data is Protected .</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100 shadow">
      <div class="card-body">
        <h5 class="card-title pb-4 border-bottom"><i class="bi bi-star"></i></h5>
        <p class="card-text mt-4">If you are someone who loves to teach, El kamelBG  can be a platform for teaching people who have an interest in your areas of expertise. Through blogging, you will not only teach others, but you will also teach yourself more about the topic.</p>
      </div>
    </div>
  </div>
</div>
</div>




    





<div class="row mt-4" id="about-section" >
<h4 class=" text-center  mt-4 mb-4 col-12 "  >About us</h4>
</div>
<div class="container mt-4  text-white rounded shadow"   id="about">
<div class="container-fluid container mt-4    ">
  <div class="row">
    <div class="col-sm-4  text-dark rounded m-4  " id="our">
      <h2>Our Story</h2>
      <h4>"The idea to craete El kamelBG is build many projects and this is one of them ,  and to get that i us the best and last technologie "</h4>
    </div>
  </div>
</div>
<div class="container-fluid bg-grey mt-4">
  <div class="row">
    <div class="col-sm-4 m-4">
      <span class="glyphicon glyphicon-globe logo"></span>
    </div>
    <div class="col-sm-4  m-4  rounded  text-dark" id="our">
      <h2>Our Values</h2>
      <h4><strong>MISSION:</strong> Our mission is ...</h4>
      <p><strong>VISION:</strong> Our vision is ...</p>
    </div>
  </div>
</div>
</div>
<div id="contact">
<h4 class=" text-center  p-4 mt-4 col-12 ">Contact us</h4>
{%  include 'contact/index.html.twig' with {form: form} only %}
</div>
</div>
{% endblock %}
{% include 'footer/footer.html.twig' %}

templates/home/show_article.html.twig
{% include ['header/header.html.twig', 'base.html.twig' ,] %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    </head>
   
    <body style="background-color: #F0F8FF">
        {% block body %}
        <div class="mt-4 container">
        <img class=" d-flex justify-content-end  " style="height: 6rem; width:25rem; margin : auto" src={{asset('media/El_KamelBG3copy.jpg')}}  alt="...">
         {% include 'article/filter.html.twig' with {form: form} only %}
        </div>
        {% for article in articles %}
        <div class="container mt-4 ">
        <div class="card m-4 w-75 p-3 shadow " >
  <div class="row g-0">
    <div class="col-md-4">
      <img style="max-width : 100% ;" src="{{ vich_uploader_asset(article, 'imageFile') }}"  >
       </div>
          <div class="col-md-8">
            <div class="card-body">
             <h4> <a href="{{ path('articles_details', {"id": article.id })}}"  style="text-decoration: none;" >{{article.title}}</a></h4>
                <p class="card-text" style="overflow-y:hidden;text-overflow:ellipsis; max-height:4.5em;">{{article.content}}</p>
                <p class="card-text"><small class="text-muted">{{article.Category}}</small></p>
                <p class="card-text"><small class="text-muted"></small></p>
                  <p class="card-text"><small class="text-muted"> <i class="bi bi-clock"></i> {{article.createdAt|date('Y-m-d H:i')}}</small></p>
              </div>
             </div>
           </div>
           </div>
        </div>
        {% endfor %}
         <div class="navigation d-flex justify-content-center mt-4">
         {{knp_pagination_render(articles)}}
      </div>
        {% endblock %}
    </body>
</html>
{% include 'footer/footer.html.twig' %}